name: SemVer Tagging

permissions:
  contents: write

on:
  pull_request:
    branches: [main, dev]

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Detect PR source and target
        id: detect
        run: |
          echo "source_branch=${{ github.head_ref }}" >> $GITHUB_OUTPUT
          echo "target_branch=${{ github.base_ref }}" >> $GITHUB_OUTPUT

      - name: Get latest SemVer tag on dev
        id: get_dev_tag
        run: |
          git fetch origin dev:dev
          tag=$(git describe --tags $(git rev-list --tags --remotes=origin/dev --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Latest dev tag: $tag"
          echo "dev_tag=$tag" >> $GITHUB_OUTPUT

      - name: Get latest SemVer tag on main
        id: get_main_tag
        run: |
          git fetch origin main:main
          tag=$(git describe --tags $(git rev-list --tags --remotes=origin/main --max-count=1) 2>/dev/null || echo "v0.0.0")
          echo "Latest main tag: $tag"
          echo "main_tag=$tag" >> $GITHUB_OUTPUT

      - name: Determine bump and tag (scripted)
        id: semver_tag
        run: scripts/tools/shell/semver_tag.sh
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
          DEV_TAG: ${{ steps.get_dev_tag.outputs.dev_tag }}
          SOURCE_BRANCH: ${{ steps.detect.outputs.source_branch }}
          TARGET_BRANCH: ${{ steps.detect.outputs.target_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}

      - name: Create and push tag
        if: steps.semver_tag.outputs.copy_tag == 'true' || steps.semver_tag.outputs.copy_tag == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          git tag ${{ steps.semver_tag.outputs.final_tag }}
          git push origin ${{ steps.semver_tag.outputs.final_tag }}
